### ISSUE TITLE
FR: Specify Type for specific file extentions

### ISSUE THREAD

**Issue by bobwng** [rexzhang/asgi-webdav#11]
Sometimes we want to open and view the file content in browser directly, for example: `.bashrc`, or `.gitignore`, but the server recognize it as `application/octet-stream`, so it would trigger the download operation while clicking such files.

So how about add an custom option, file types mapping?

e.g. we can map all files matching pattern ".gitignore" or ".*rc" as "text/plain", and the we can just click to view the content directly in the brower.

**Comment by rexzhang** [comment]
at first, please upgrade your ASGI-WebDAV instance to newest version.
2nd, change your `webdav.json` like blow:
```
{
  "guess_type_extension": {
    "filename_mapping": {
      ".bashrc": "text/plain"
    },
    "suffix_mapping": {
      ".py": "text/plain"
    }
  }
}
```
well, done.

default value `DEFAULT_FILENAME_CONTENT_TYPE_MAPPING` and `DEFAULT_SUFFIX_CONTENT_TYPE_MAPPING` defined in file [`constants.py`](https://github.com/rexzhang/asgi-webdav/blob/main/asgi_webdav/constants.py) .

config file example at [here](https://github.com/rexzhang/asgi-webdav/blob/main/examples/specify_type_for_specific_file_extentions.json)
