### ISSUE TITLE
webdav.json: unencrypted passwords

### ISSUE THREAD

**Issue by plashenkov** [rexzhang/asgi-webdav#12]
Hi there!
Thanks for the nicest WebDAV server!

Is it possible to specify passwords in `webdav.json` in some encrypted format? Or is it possible to use htpasswd/htdigest file?
That's not fine that passwords in `webdav.json` are open.

**Comment by rexzhang** [comment]
It isn't necessary, I recommend this configuration

```
{
	"provider_mapping":[
		{
		    "prefix":"/",
		    "uri":"file:///data/root"
		},
		{
}
```

the `webdav.json` in `file:///data`

I have better solution, LDAP or other like. but it is just a plan

**Comment by plashenkov** [comment]
Hi @rexzhang 
Thank you!

Sorry, I do not understand your `provider_mapping` example.
I know that we can create `webdav.json` in /data directory. I have read the docs, for sure.

I am speaking about the fact that we have to specify all passwords in `webdav.json` in unprotected, plain text format. So if someone hacks the server, he can find and see all the passwords.

htpasswd would be a good addition regardless LDAP, etc. Because this is so standard way to define users and passwords.
Or maybe you can allow specifying passwords right in `webdav.json`, but in some encrypted format (bcrypt or something like). That would be really enough to solve the problem.

P.S. Thanks for this project, it is so good working.
Even the most popular `bytemark/webdav` has problems with Windows Explorer, while your project works nice!

**Comment by rexzhang** [comment]
There are three ways to protect the password on the disk;
1. symmetric encryption. ASGI WebDAV is open-source software, so, it is a joke
2. asymmetric encryption. yes, it is a good way or enough way, but, this way will affect the performance of EACH HTTP REQUEST.
3. don't save passwords on the disk. safe and no performance problems. so, I choose OpenLDAP or others like

Of course, performance, security, simple, this is the choice of system admin. but I don't have enough time to do all the features, sorry

**Comment by rexzhang** [comment]
This feature has so many codes shared with OpenLDAP, so I made it. ;-) b9784d2b0c7b628296e629592b704706d433c457

**Comment by rexzhang** [comment]
released
