### ISSUE TITLE
macOS: DS_Store files

### ISSUE THREAD

**Issue by plashenkov** [rexzhang/asgi-webdav#13]
As you know, macOS Finder creates garbage DS_Store files by default. Currently, ASGI WebDAV Server doesn't show them in web interface, but files are actually created. So, Windows users will see them.

Is it possible or is it a good idea at all to add some option to prevent these files from being created? I.e. when a client creates any other files and folder, the server allows this, but when it tries to create DS_Store files — it prevents.

P.S. Yes, there is an option in macOS to disable DS_Store files creation in network stores, but we cannot force all users to turn this option on. So, the server capability to handle this would be really nice.

**Comment by rexzhang** [comment]
Maybe, Filter the file list based on user-agent in PROPFIND method? like [GET method](https://github.com/rexzhang/asgi-webdav/blob/4689c0a34855b3ada5724ff398e6af41b8a21b56/asgi_webdav/web_dav.py#L376). Caesar's to Caesar ;-)

Of course, It is option in the config file

**Comment by rexzhang** [comment]
231c233df58456e81b7264a65c1bce7d37047d19, done

**Comment by plashenkov** [comment]
Thank you!

**Comment by rexzhang** [comment]
release
