### ISSUE TITLE
How to run without Docker?

### ISSUE THREAD

**Issue by bootrino** [rexzhang/asgi-webdav#17]
Hello Could you please provide instructions on the README explaining how to start this without using docker thanks.

**Comment by rexzhang** [comment]
please visit [here](http://127.0.0.1:9999/install/)

**Comment by bootrino** [comment]
Hi Rex that link doesn't work.

**Comment by rexzhang** [comment]
sorr, it's [here](https://rexzhang.github.io/asgi-webdav/install/)
