### ISSUE TITLE
PyPI package

### ISSUE THREAD

**Issue by davidbrochart** [rexzhang/asgi-webdav#22]
It seems `asgi-webdav` has not been published on PyPI yet.
Do you think you can do it?

**Comment by rexzhang** [comment]
No one has asked for it yet

**Comment by davidbrochart** [comment]
I would need it to be able to use it in my project.
I can publish it with my account if you want.

**Comment by rexzhang** [comment]
I will do it

**Comment by rexzhang** [comment]
[Done!](https://pypi.org/project/ASGIWebDAV/)

**Comment by rexzhang** [comment]
Later I will use other libraries to replace bonsai. bonsai has a lot of dependency issues
