### ISSUE TITLE
Support Python >=3.7

### ISSUE THREAD

**Issue by davidbrochart** [rexzhang/asgi-webdav#26]
Any reason for requiring [Python >=3.10](https://github.com/rexzhang/asgi-webdav/blob/87b7b0e3917336acca35457aad238d5b49a16be7/setup.py#L166)?

**Comment by rexzhang** [comment]
Personal preference, sorry

**Comment by rexzhang** [comment]
maybe, because [this](https://www.python.org/dev/peps/pep-0604)
