### ISSUE TITLE
There is no dist folder?

### ISSUE THREAD

**Issue by changfeng98** [rexzhang/asgi-webdav#3]
When I install it , there is a error: ERROR: Could not install packages due to an EnvironmentError: [Errno 2] 没有那个文件或目录: '/home/ubuntu/Desktop/asgi-webdav/dist/ASGI_WebDAV-0.7.0-py2.py3-none-any.whl'. 
So do you forget to upload the file or folder???

**Comment by rexzhang** [comment]
抱歉这个地方代码写死了，当前版本是 0.9.1 ，请执行
```
pip install dist/ASGI_WebDAV-0.9.1-py2.py3-none-any.whl
```

**Comment by rexzhang** [comment]
Fixed
