### ISSUE TITLE
Pass external logging configuration

### ISSUE THREAD

**Issue by davidbrochart** [rexzhang/asgi-webdav#31]
Is there a way to disable logging, or at least reduce the level? I tried this but it doesn't seem to work:
```py
config = init_config_from_obj(webdav_conf)
config.logging_level = LoggingLevel.CRITICAL
```

**Comment by davidbrochart** [comment]
Ah actually this works:
```py
webdav_conf.update(logging_level=LoggingLevel.CRITICAL)
init_config_from_obj(webdav_conf)
```

**Comment by davidbrochart** [comment]
Actually what I'd like is to integrate asgi-webdav into a framework that already has its own [logging configuration](https://asphalt.readthedocs.io/en/latest/userguide/deployment.html#writing-a-configuration-file). Currently asgi-webdav duplicates all the uvicorn messages that Asphalt prints. I'm not sure how to do that.

**Comment by rexzhang** [comment]
`Config.logging.enable == False` will disable log info, now. 6c9885c56c07ff01778d60dfb1e06fa4af18ee7e

**Comment by davidbrochart** [comment]
Thanks!
