### ISSUE TITLE
怎么修改容器新建文件权限为 666？

### ISSUE THREAD

**Issue by Gloryandel** [rexzhang/asgi-webdav#38]
求助大佬，怎么修改容器新建文件权限为 666？默认的 umask 为 022，修改了容器内的 root，runner 用户的 umaks 均无效。。。，新建文件权限还是 644

**Comment by rexzhang** [comment]
unmask 设置的是容器内 root 用户的行为吧? runner 不是容器内 root 用户,如果需要做这类控制,可能需要专门做 rootless 的 docker 镜像

**Comment by Gloryandel** [comment]
> 

"runner 不是容器内 root 用户"，感谢大佬提点，听说 Docker 可以设置 umask 环境变量，但是我试了很多容器，好像没什么效果，默认 umask 还是 022。Docker 是不能设置吗？这个问题可以关了😂

**Comment by rexzhang** [comment]
如果是为了控制runner实际对应的用户来解决权限和安全问题；可以用UID/GID环境变量。
一般都是开issue的认为解决了关…

**Comment by rexzhang** [comment]
那试试把 UID/GID 设置为 unraid 的 nobody 的 id?

**Comment by rexzhang** [comment]
命令行里面用
```
id nobody
uid=65534(nobody) gid=65534(nogroup) groups=65534(nogroup
```

**Comment by Gloryandel** [comment]
👍,至少新建文件夹对是 nobody 了

**Comment by rexzhang** [comment]
旧文件，可能需要在unraid中用

chown nobody.nobody -R *

处理下
