### ISSUE TITLE
Release update to Pydantic v2

### ISSUE THREAD

**Issue by davidbrochart** [rexzhang/asgi-webdav#39]
How do you feel about making a release with the [update to Pydantic v2](https://github.com/rexzhang/asgi-webdav/commit/d9d1c593737cfe512605472fbdd98edbffe0d0f9)?

**Comment by davidbrochart** [comment]
Great if it's planned (not urgent).

**Comment by rexzhang** [comment]
[done](https://pypi.org/project/ASGIWebDAV/1.4.0/)
