### ISSUE TITLE
Use AnyIO

### ISSUE THREAD

**Issue by davidbrochart** [rexzhang/asgi-webdav#41]
I see that `ASGIWebDAV` uses [aiofiles](https://github.com/mosquito/aiofile), which is asyncio-only.
It could use [AnyIO](https://anyio.readthedocs.io/en/stable/fileio.html) for async file I/O, allowing this project to also be compatible with [Trio](https://github.com/python-trio/trio). What do you think?

**Comment by rexzhang** [comment]
I don't know much about Trio, are there any special advantages?

**Comment by davidbrochart** [comment]
Yes, Trio and AnyIO implement [structured concurrency](https://vorpus.org/blog/notes-on-structured-concurrency-or-go-statement-considered-harmful). Major projects like [FastPI and Starlette are based on AnyIO](https://fastapi.tiangolo.com/async/?h=anyio#write-your-own-async-code).

**Comment by rexzhang** [comment]
Thank you very much for your feedback.

Trio and AnyIO are good, but [aiofiles isn't compatible with AnyIO](https://github.com/agronholm/anyio/issues/266). This means that ASGI-WebDAV needs to completely rewrite the `FileSystemProvider`. This is a bit of a workload.

I've been looking at cython/mypyc lately, and I don't want to introduce any third-party libraries that might cause incompatibilities until then. So I don't think we should support AnyIO for now.

**Comment by davidbrochart** [comment]
But the point would be to replace `aiofiles` with AnyIO's asynchronous file I/O and path operations. I could open a PR, this is really a simple change.
