### ISSUE TITLE
在ghcr上发布容器镜像

### ISSUE THREAD

**Issue by bonjour-py** [rexzhang/asgi-webdav#42]
请问有计划在ghcr 发布容器镜像么。
目前dockerHub在国内全都断掉了

**Comment by rexzhang** [comment]
现在的[Github action](https://github.com/rexzhang/asgi-webdav/blob/main/.github/workflows/release-dockerhub.yml)简单改一下就能自动发布到ghcr;不过我不知道如何用一个action同时发布到两个地方.实在不行可以搞两个,不过就是有点丑陋

**Comment by bonjour-py** [comment]
![图片](https://github.com/rexzhang/asgi-webdav/assets/33248848/f9e30d70-130f-4350-8c56-c570179ab16e)

参考： https://docs.github.com/zh/actions/publishing-packages/publishing-docker-images
明天我来交pr
