### ISSUE TITLE
My project talks to your server

### ISSUE THREAD

**Issue by bootrino** [rexzhang/asgi-webdav#7]
Hello thanks for this library - I built React Oxide using it: https://github.com/bootrino/reactoxide

**Comment by rexzhang** [comment]
you're welcome, how can i help you?

**Comment by bootrino** [comment]
The only suggestion I have is for you to ensure your install documentation is up to date and has been tested.

Apart from that your server works well.

Perhaps you could put a link to the React Oxide project on your projects README.MD?

**Comment by rexzhang** [comment]
done 66fb38aff35c43bb65f89be819bb681552620ebe
